export interface Recipe {
  id: number;
  title: string;
  description: string;
  image: string;
  content: string;
  slug: string;
}

export const recipes: Recipe[] = [
  {
    id: 1,
    title: "Perfect Chicken karahi ",
    description: "Chicken Karahi is a signature dish bursting with vibrant flavors. Its rich, spicy gravy and tender chicken make it a favorite in Pakistani households and a must-try for food lovers worldwide.",
    image: "/Food1.jpg",
    slug: "chicken-karahi",
content: "  Chicken Karahi is a beloved Pakistani dish celebrated for its rich and bold flavors. To prepare, begin by heating oil or ghee in a wok or deep pan over medium heat. Add a teaspoon of cumin seeds and let them splutter for a few seconds to release their aroma. Next, add chicken pieces (about 1 kg, cut into medium pieces) and cook on high heat, stirring occasionally, until the chicken turns light brown. Stir in 2 tablespoons of ginger-garlic paste and sauté for a minute or two until fragrant.Now, add finely chopped or pureed tomatoes (5-6 large), red chili powder (1 teaspoon), turmeric powder (½ teaspoon), coriander powder (1 teaspoon), and salt to taste. Mix everything well and cover the pan. Let the mixture cook on medium heat until the tomatoes break down and the oil separates from the masala, which usually takes about 10-15 minutes. Stir occasionally to prevent sticking.Once the base is ready, reduce the heat and mix in ½ cup of yogurt and 4-5 slit green chilies. Cook for another 7-10 minutes, allowing the flavors to meld beautifully. As the chicken cooks through and absorbs the spices, you’ll notice the gravy thickening. When the chicken is tender, sprinkle ½ teaspoon of garam masala powder on top and garnish with freshly chopped coriander leaves and julienned ginger for a burst of freshness.For a unique smoky flavor, you can place a piece of hot charcoal in the pan, drizzle a teaspoon of oil over it, and immediately cover the pan for 2-3 minutes. Serve your Chicken Karahi hot with naan, roti, or steamed rice, and enjoy a dish that captures the essence of Pakistani cuisine.   "
},

  {
    id: 2,
    title: "Traditional Gulab jamun recipe",
    description: "Gulab Jamun is a classic Indian dessert made from milk solids, soaked in a sweet syrup flavored with cardamom and rose water.",
    image: "/Food3.webp",
    slug: "gulab-jamun",
    content: "   Gulab Jamun, a timeless South Asian delicacy, is renowned for its rich flavor, soft texture, and irresistible sweetness, making it a centerpiece of festive occasions and celebrations. To prepare this traditional dessert, start by making the dough using khoya (200 grams, finely grated), 2 tablespoons of all-purpose flour, a pinch of baking soda, and 2-3 tablespoons of milk. Mix the ingredients gently until the mixture comes together into a soft, smooth dough, ensuring not to overwork it. Divide the dough into small, equal-sized portions and roll them into smooth, crack-free balls.For the sugar syrup, combine 2 cups of sugar with 1½ cups of water in a saucepan. Heat gently until the sugar dissolves completely, then add a few cardamom pods, a splash of rose water, and a pinch of saffron for an aromatic and flavorful syrup. Let it simmer for a few minutes and keep it warm on low heat.Heat oil or ghee in a deep pan on low to medium heat for frying. Carefully add the dough balls and fry them, stirring gently, until they turn a uniform golden brown. The key is to fry them on low heat to ensure they cook evenly without burning. Once fried, remove the gulab jamun balls and place them on a paper towel briefly to remove excess oil.While they are still warm, transfer the gulab jamun into the warm sugar syrup and let them soak for at least 2-3 hours, allowing them to absorb the syrup fully. Serve warm or at room temperature, garnished with chopped pistachios or almonds for an added touch of elegance.Gulab Jamun is more than just a dessert; it represents the essence of tradition and hospitality. Its soft, syrupy texture and luxurious taste bring comfort and delight, making it a symbol of joy and togetherness in South Asian culture. Whether served at weddings, festivals, or family gatherings, Gulab Jamun continues to be a cherished treat that transcends generations."
  },
  {
    id: 3,
    title: "Everyone's Favorite Biryani",
    description: "Biryani is a flavorful and aromatic rice dish made with layers of marinated meat, fragrant rice, and a blend of spices.",
    image: "/Food2.avif",
    slug: "Biryani",
    content:"  Chicken Biryani is a beloved and aromatic South Asian dish that perfectly combines tender chicken, fragrant basmati rice, and a symphony of spices, making it an all-time favorite for special occasions. To prepare an authentic and delicious Chicken Biryani, start by marinating 1 kg of chicken pieces with 1 cup of yogurt, 2 tablespoons of ginger-garlic paste, 1 teaspoon each of red chili powder, turmeric powder, and coriander powder, ½ teaspoon of garam masala, and salt to taste. Add freshly squeezed lemon juice and a handful of fried onions to enhance the flavor. Let the chicken marinate for at least an hour or overnight for best results.In a heavy-bottomed pot, heat ½ cup of oil or ghee, and sauté whole spices such as bay leaves, cinnamon sticks, cloves, cardamom pods, and star anise until fragrant. Add sliced onions and cook until golden brown, then stir in the marinated chicken. Cook the chicken on medium heat until it is partially cooked and the masala is rich and aromatic.While the chicken cooks, rinse and soak 3 cups of basmati rice for 30 minutes. In a separate pot, boil water with salt and whole spices, then add the soaked rice. Cook the rice until it is 70% done, then drain it and set it aside.To layer the biryani, spread a layer of the partially cooked chicken at the bottom of the pot, followed by a layer of the parboiled rice. Sprinkle saffron milk (a pinch of saffron soaked in 2 tablespoons of warm milk), fried onions, chopped mint, and coriander leaves between layers. Repeat the layering process, ending with a top layer of rice.Cover the pot tightly with a lid, sealing it with dough or foil to trap the steam. Cook the biryani on low heat (dum) for about 25-30 minutes, allowing the flavors to meld and the rice to fully absorb the chickens juices and spices. Ensure the flame is low to prevent burning.Once cooked, gently fluff the biryani to mix the layers without breaking the rice grains. Serve hot with raita, salad, or a side of pickle for a complete and indulgent meal. This Chicken Biryani, with its rich aroma and exquisite taste, is guaranteed to transport you to the heart of South Asian culinary tradition"
  },
  {
    id: 4,
    title: "Desi Sarson ka Sag",
    description: "Sarson Ka Saag is a beloved Punjabi dish made from mustard greens, spinach, and spices, cooked to perfection with a dollop of butter.",
    image: "/Food5.jpg",
    slug: "Sag",
    content:" Sarson ka Saag, a classic Punjabi delicacy, is a wholesome and flavorful dish made from mustard greens and a medley of other greens, cooked with aromatic spices and served with makki di roti (cornbread). It is not just a dish but a symbol of Punjabi culture and rural traditions, often enjoyed during the winter months. Its nutritional value and comforting taste make it a cherished recipe across generations.To prepare authentic sarson ka saag, start by cleaning and washing 500 grams of mustard greens (sarson), 250 grams of spinach (palak), and 100 grams of bathua (wild spinach). Roughly chop the greens and boil them in a large pot with 1 cup of water, a small piece of ginger, and 2-3 green chilies. Add a pinch of salt and a tablespoon of maize flour (makki ka atta) to the pot, which helps to thicken the saag and enhances its earthy flavor. Cook the greens on low heat for about 30-40 minutes, stirring occasionally, until they are soft and well-blended.Once cooked, allow the greens to cool slightly and then blend them into a coarse puree. The texture should remain slightly chunky for an authentic feel.For the tempering, heat 3-4 tablespoons of ghee in a pan. Add finely chopped onions and garlic and sauté until golden brown. Stir in chopped tomatoes and cook until they turn soft and the oil separates. Add a pinch of red chili powder and garam masala for a subtle kick, and mix this tempering into the prepared saag. Simmer the saag for another 10-15 minutes, adjusting the seasoning as needed.Serve hot sarson ka saag with freshly made makki di roti, a dollop of homemade butter or ghee, and a side of jaggery (gur) or pickled onions for a complete and satisfying meal.The value of sarson ka saag lies not only in its robust and earthy taste but also in its high nutritional content. Rich in iron, calcium, and dietary fiber, it provides essential nutrients that support health during the colder months. Moreover, it embodies the simplicity and heartiness of rural Punjabi cuisine, connecting people to their roots and traditions. A plate of sarson ka saag with makki di roti is more than a meal—it’s an experience of culture, warmth, and nostalgia. "
  },
  {
    id: 5,
    title: "Delicious Beef Nihari",
    description: "Beef Nihari is a rich, aromatic stew, slow-cooked with tender beef shank and a blend of spices. This hearty dish is a quintessential part of Pakistani cuisine.",
    image: "/Food7.webp",
    slug: "Nihari",
    content:"Beef Nihari, a quintessential Pakistani dish, is a slow-cooked stew with rich, aromatic spices and melt-in-your-mouth beef shank. Known for its luxurious texture and bold flavors, Nihari is a beloved comfort food often enjoyed at breakfast or special occasions.To prepare authentic Beef Nihari, begin by heating ½ cup of oil or ghee in a heavy-bottomed pot. Add 1 kg of beef shank pieces and sauté until lightly browned. Remove the meat and set aside. In the same pot, add 2 finely sliced onions and fry until golden brown. Stir in 2 tablespoons of ginger-garlic paste and sauté for a minute.Next, add 2 tablespoons of Nihari spice mix (or a blend of ground fennel, coriander, cumin, cinnamon, cloves, and nutmeg) along with 1 teaspoon of red chili powder, ½ teaspoon turmeric powder, and salt to taste. Toast the spices briefly before adding the beef back to the pot. Stir to coat the meat with the spices.Add 6-8 cups of water and bring it to a boil. Cover the pot and let the beef simmer on low heat for 4-5 hours until it becomes tender and the flavors meld beautifully. For a quicker alternative, you can use a pressure cooker, reducing the cooking time to about an hour.To thicken the stew, dissolve 3 tablespoons of wheat flour (atta) in water to form a smooth paste, and stir it into the Nihari. Simmer for another 20-30 minutes until the gravy reaches a silky consistency. Adjust the seasoning and consistency as desired.For the finishing touch, garnish the Nihari with julienned ginger, fresh coriander leaves, and green chilies. Serve hot with naan or paratha, accompanied by lemon wedges for a zesty kick.Beef Nihari is not just a dish; it’s a cultural icon, revered for its deep, comforting flavors and traditional slow-cooking method. Its rich aroma and tender meat make it an unforgettable culinary experience, symbolizing the warmth and hospitality of South Asian cuisine. "
  },
  {
    id: 6,
    title: "Bessan kadhi Pakora",
    description: "Kadhi Pakoda is a traditional dish made with gram flour and yogurt-based curry, complemented by soft, fried pakoras (fritters).",
    image: "/Food6.webp",
    slug: "kadhi",
    content:" To make Kadhi Pakora, begin by preparing the pakoras, which are crispy gram flour fritters that will soak up the rich, spiced yogurt gravy. In a large mixing bowl, combine 1 cup gram flour (besan), 1 small onion finely chopped, 1-2 green chilies chopped, 1 teaspoon cumin seeds, 1 teaspoon red chili powder, ½ teaspoon turmeric powder, ½ teaspoon carom seeds (ajwain), and salt to taste. Gradually add water to form a thick batter that holds its shape. To enhance the flavor, you can add fresh coriander leaves chopped into the batter. Heat oil in a deep pan over medium heat. Once hot, drop spoonfuls of the batter into the oil, ensuring they don’t stick to each other. Fry the pakoras until they turn golden brown and crispy, about 4-5 minutes. Remove them from the oil and place them on a paper towel to drain excess oil. Set them aside while you prepare the kadhi.For the kadhi, whisk together 1 cup yogurt and 3 tablespoons gram flour (besan) until smooth, and add water to achieve a slightly runny consistency. Heat 2-3 tablespoons oil in a large pan over medium heat. Add 1 teaspoon cumin seeds, 1 teaspoon mustard seeds, and 1-2 dried red chilies. Let them splutter for a few seconds. Then, add 4-5 curry leaves (optional) and sauté for a minute until the spices release their aroma. Add 1 teaspoon ginger-garlic paste and sauté until fragrant, about 30 seconds. Next, pour in the yogurt and gram flour mixture, stirring constantly to prevent lumps from forming. Add 1 teaspoon turmeric powder, 1 teaspoon red chili powder, and salt to taste. Bring the mixture to a boil while stirring frequently. Once it reaches a boil, reduce the heat and let it simmer for 15-20 minutes. Stir occasionally to avoid the kadhi from sticking to the bottom of the pan. The kadhi should thicken slightly as it cooks.Once the kadhi has reached the desired consistency, gently add the fried pakoras to the simmering gravy. Let them soak in the kadhi for about 10-15 minutes so the pakoras absorb the flavors of the gravy. If the kadhi becomes too thick, you can add a bit more water to achieve the right consistency. Before serving, garnish with fresh coriander leaves for a burst of color and freshness. Serve the Kadhi Pakora hot with steamed rice or naan for a comforting, flavorful meal. The combination of crispy pakoras soaked in the tangy, spiced yogurt gravy is a perfect blend of textures and flavors, making this dish a beloved classic in North Indian and Pakistani cuisine. "
  },
]



export async function getRecipe(slug: string): Promise<Recipe | undefined> {
  return recipes.find(recipe => recipe.slug === slug);
}

export async function getAllRecipes(): Promise<Recipe[]> {
  return recipes;
}